// <auto-generated />
using AnimalShelterApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AnimalShelterApi.Migrations
{
    [DbContext(typeof(AnimalShelterApiContext))]
    [Migration("20230331190200_AddInitial")]
    partial class AddInitial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AnimalShelterApi.Models.Cat", b =>
                {
                    b.Property<int>("CatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AgeMonths")
                        .HasColumnType("int");

                    b.Property<int>("AgeYears")
                        .HasColumnType("int");

                    b.Property<string>("Breed")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Coloring")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("DateAvailable")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("CatId");

                    b.ToTable("Cats");

                    b.HasData(
                        new
                        {
                            CatId = 1,
                            AgeMonths = 6,
                            AgeYears = 0,
                            Breed = "Domestic Short Hair",
                            Coloring = "Orange/White",
                            DateAvailable = "4/10/2023",
                            Description = "Playful orange kitten Matilda came to us with her brother Rexie",
                            Name = "Matilda",
                            Sex = "Female",
                            Weight = 3
                        },
                        new
                        {
                            CatId = 2,
                            AgeMonths = 6,
                            AgeYears = 0,
                            Breed = "Domestic Short Hair",
                            Coloring = "Gray/White",
                            DateAvailable = "4/10/2023",
                            Description = "Mellow kitten Rexie came to us with his sister Matilda",
                            Name = "Rexie",
                            Sex = "Male",
                            Weight = 4
                        });
                });

            modelBuilder.Entity("AnimalShelterApi.Models.Dog", b =>
                {
                    b.Property<int>("DogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AgeMonths")
                        .HasColumnType("int");

                    b.Property<int>("AgeYears")
                        .HasColumnType("int");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Coloring")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("DateAvailable")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("DogId");

                    b.ToTable("Dogs");

                    b.HasData(
                        new
                        {
                            DogId = 1,
                            AgeMonths = 6,
                            AgeYears = 2,
                            Breed = "Boxer/Mix",
                            Coloring = "Brown/White",
                            DateAvailable = "4/15/2023",
                            Description = "Fun guy Danny loves chasing bugs and taking naps",
                            Name = "Danny",
                            Sex = "Male",
                            Weight = 60
                        },
                        new
                        {
                            DogId = 2,
                            AgeMonths = 9,
                            AgeYears = 0,
                            Breed = "Labrador",
                            Coloring = "Yellow",
                            DateAvailable = "4/16/2023",
                            Description = "Mary is a sweet puppy who loves playing with kittens Matilda and Rexie",
                            Name = "Mary",
                            Sex = "Female",
                            Weight = 35
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
